1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: -1
  num_trials: 10
  parameter_constraints: []
  parameters: []
  sobol_seed: 0
console:
  format: {}
  quiet: false
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      size: 20000
      type: triples
    test_without_unseen:
      filename: test_without_unseen.del
      size: 20000
      type: triples
    train:
      filename: train.del
      size: 5780246
      type: triples
    train_sample:
      filename: train_sample.del
      size: 20000
      type: triples
    valid:
      filename: valid.del
      size: 20000
      type: triples
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 20000
      type: triples
  name: fbwq_full
  num_entities: 1886683
  num_relations: 572
  pickle: true
entity_ranking:
  chunk_size: -1
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: false
  tie_handling:
    atol: 1e-05
    rtol: 1e-04
    type: rounded_mean_rank
    warn_only: true
eval:
  batch_size: 32
  num_workers: 5
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- simple
job:
  device: cuda
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 100
  dropout: 0.0
  initialize: normal_
  initialize_args:
    +++: +++
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: simple
modules:
- kge.job
- kge.model
- kge.model.embedder
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: auto
  num_samples:
    o: -1
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
search:
  device_pool:
  - cuda:0
  - cuda:1
  - cuda:2
  - cuda:3
  num_workers: 1
  on_error: abort
  type: ax_search
simple:
  class_name: SimplE
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    type: lookup_embedder
train:
  abort_on_nan: true
  auto_correct: false
  batch_size: 32
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: .nan
  lr_scheduler: ''
  lr_scheduler_args:
    +++: +++
  lr_warmup: 0
  max_epochs: 5
  num_workers: 5
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.1
        weight_decay: 4.0e-08
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: true
  subbatch_size: -1
  trace_level: epoch
  type: KvsAll
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
user:
  +++: +++
valid:
  early_stopping:
    patience: 5
    threshold:
      epochs: 0
      metric_value: 0.0
  every: 1
  metric: mean_reciprocal_rank_filtered
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
